/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import NhacCuaToi.TaoPlaylist;
import entity.AccountData;
import entity.BaiHatEntity;
import saveEvent.MusicDetails;
import utils.EventManager;

/**
 *
 * @author TRONG NGHIA
 */
public class TaoMoiPlaylist extends javax.swing.JFrame {

    MusicDetails manager;

    /**
     * Creates new form TaoPlaylist
     */
    public TaoMoiPlaylist() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public interface CreatePlaylistListener {

        void onCreatePlaylist(String playlistName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDong = new javax.swing.JLabel();
        buttonOutLine2 = new swing.ButtonOutLine();
        textPlaylistNew = new swing.TextPlaylistNew();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(29, 38, 49));

        lbDong.setBackground(new java.awt.Color(29, 38, 49));
        lbDong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbDong.setForeground(new java.awt.Color(204, 51, 0));
        lbDong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDong.setText("X");
        lbDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDong.setOpaque(true);
        lbDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDongMouseClicked(evt);
            }
        });

        buttonOutLine2.setForeground(new java.awt.Color(255, 255, 255));
        buttonOutLine2.setText("Tạo mới playlist");
        buttonOutLine2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonOutLine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOutLine2MouseClicked(evt);
            }
        });
        buttonOutLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbDong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPlaylistNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOutLine2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbDong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(textPlaylistNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOutLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDongMouseClicked
        dispose();
    }//GEN-LAST:event_lbDongMouseClicked

    private void buttonOutLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine2ActionPerformed
        String ten = textPlaylistNew.getText();
        AccountData.setTenPlaylist(ten);
    }//GEN-LAST:event_buttonOutLine2ActionPerformed

    private void buttonOutLine2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOutLine2MouseClicked
        EventManager.addListener(FormTrangChu.DETAILS_SELECTED_EVENT, (event, data) -> {
            if (data instanceof BaiHatEntity) {
                BaiHatEntity selectedBaiHat = (BaiHatEntity) data;
                manager = new MusicDetails();
                manager.setSelectedBaiHat(selectedBaiHat);
            }
        });
    }//GEN-LAST:event_buttonOutLine2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoMoiPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoMoiPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoMoiPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoMoiPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoMoiPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonOutLine buttonOutLine2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDong;
    private swing.TextPlaylistNew textPlaylistNew;
    // End of variables declaration//GEN-END:variables
}
